# Generated by Django 5.2.1 on 2025-06-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createpost', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Education', 'Education'), ('News', 'News')], max_length=50),
        ),
    ]
